# Protect Invalidate All Established Security and Set Security Controls
# Switch in the public restriction map too, so they are reachable only over
# ACS Data In.
CONFIG_SAMPLE_ACS_PROTECT_SECURITY_OPS=y
