/*
 * Copyright (c) 2025 Dipak Shetty
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <zephyr/bluetooth/services/acs.h>

#include "acs_cp.h"
#include "acs_internal.h"

#include <zephyr/logging/log.h>
LOG_MODULE_DECLARE(bt_acs, CONFIG_BT_ACS_LOG_LEVEL);

static const struct bt_acs_feature_rsp acs_features = {
	.features = (
		/* Mandatory: Spec requires at least one of these two to be 1 */
		(IS_ENABLED(CONFIG_BT_ACS_DESCRIPTORS) ? BT_ACS_FEATURE_DESCRIPTORS_SUPPORTED : 0) |
		(IS_ENABLED(CONFIG_BT_ACS_RESOURCE_HANDLE_UUID_MAP)
			 ? BT_ACS_FEATURE_RESOURCE_HANDLE_TO_UUID_MAP_SUPPORTED
			 : 0) |

		/* Optional Features */
		(IS_ENABLED(CONFIG_BT_ACS_MULTIPLE_RESTRICTION_MAPS)
			 ? BT_ACS_FEATURE_MULTIPLE_RESTRICTION_MAPS_SUPPORTED
			 : 0) |
		(IS_ENABLED(CONFIG_BT_ACS_ATT_MTU) ? BT_ACS_FEATURE_ATT_MTU_SUPPORTED : 0) |

		/* Security Management Procedures (Table 4.13: C.6, C.8, C.9) */
		(IS_ENABLED(CONFIG_BT_ACS_INVALIDATE_ESTABLISHED_SECURITY)
			 ? BT_ACS_FEATURE_INVALIDATE_ESTABLISHED_SECURITY_SUPPORTED
			 : 0) |
		(IS_ENABLED(CONFIG_BT_ACS_SET_SECURITY_CONTROLS_SWITCH)
			 ? BT_ACS_FEATURE_SET_SECURITY_CONTROLS_SWITCH_SUPPORTED
			 : 0) |
		(IS_ENABLED(CONFIG_BT_ACS_INITIATE_PAIRING)
			 ? BT_ACS_FEATURE_INITIATION_OF_PAIRING_SUPPORTED
			 : 0) |
		/* Key Exchange Methods */
		(IS_ENABLED(CONFIG_BT_ACS_KEY_EXCHANGE_ECDH)
			 ? BT_ACS_FEATURE_ECDH_KEY_EXCHANGE_SUPPORTED
			 : 0) |
		(IS_ENABLED(CONFIG_BT_ACS_KEY_EXCHANGE_KDF)
			 ? BT_ACS_FEATURE_KDF_KEY_EXCHANGE_SUPPORTED
			 : 0) |

		/* Resource Protection Types */
		(IS_ENABLED(CONFIG_BT_ACS_PROTECTED_RESOURCE_WRITE)
			 ? BT_ACS_FEATURE_PROTECTED_RESOURCE_USES_WRITE_REQUEST
			 : 0) |
		(IS_ENABLED(CONFIG_BT_ACS_PROTECTED_RESOURCE_READ)
			 ? BT_ACS_FEATURE_PROTECTED_RESOURCE_USES_READ_REQUEST
			 : 0) |
		(IS_ENABLED(CONFIG_BT_ACS_PROTECTED_RESOURCE_NOTIFICATION)
			 ? BT_ACS_FEATURE_PROTECTED_RESOURCE_USES_NOTIFICATION
			 : 0) |
		(IS_ENABLED(CONFIG_BT_ACS_PROTECTED_RESOURCE_INDICATION)
			 ? BT_ACS_FEATURE_PROTECTED_RESOURCE_USES_INDICATION
			 : 0) |

		/* Key Formats (Applying selection to both Server and Client bits) */
		(IS_ENABLED(CONFIG_BT_ACS_KEY_FORMAT_UNCOMPRESSED)
			 ? (BT_ACS_FEATURE_KEY_FORMAT_AC_SERVER_UNCOMPRESSED_PLAIN_SUPPORTED |
			    BT_ACS_FEATURE_KEY_FORMAT_AC_CLIENT_UNCOMPRESSED_PLAIN_SUPPORTED)
			 : 0) |
		(IS_ENABLED(CONFIG_BT_ACS_KEY_FORMAT_X509)
			 ? (BT_ACS_FEATURE_KEY_FORMAT_AC_SERVER_X509_SUPPORTED |
			    BT_ACS_FEATURE_KEY_FORMAT_AC_CLIENT_X509_SUPPORTED)
			 : 0) |
		(IS_ENABLED(CONFIG_BT_ACS_KEY_FORMAT_MANUFACTURER)
			 ? (BT_ACS_FEATURE_KEY_FORMAT_AC_SERVER_MANUFACTURER_SPECIFIC_SUPPORTED |
			    BT_ACS_FEATURE_KEY_FORMAT_AC_CLIENT_MANUFACTURER_SPECIFIC_SUPPORTED)
			 : 0)),

	.protection_methods =
		((IS_ENABLED(CONFIG_BT_ACS_FEAT_CONFIDENTIALITY)
			  ? BT_ACS_PROTECTION_CONFIDENTIALITY_SUPPORTED
			  : 0) |
		 (IS_ENABLED(CONFIG_BT_ACS_FEAT_INTEGRITY) ? BT_ACS_PROTECTION_INTEGRITY_SUPPORTED
							   : 0) |
		 (IS_ENABLED(CONFIG_BT_ACS_FEAT_AUTHENTICATION)
			  ? BT_ACS_PROTECTION_AUTHENTICATION_SUPPORTED
			  : 0) |
		 (IS_ENABLED(CONFIG_BT_ACS_FEAT_AUTHORIZATION)
			  ? BT_ACS_PROTECTION_AUTHORIZATION_SUPPORTED
			  : 0)),

	.oob_key_exchange_capabilities = 0U,

	.confirmation_static_oob_number_capabilities = 0U,

	/* Numeric confirmation input capabilities */
	.confirmation_input_oob_number_max_value = CONFIG_BT_ACS_CONFIRMATION_INPUT_MAX_VALUE,
	.confirmation_input_oob_number_capabilities =
		((IS_ENABLED(CONFIG_BT_ACS_CONFIRMATION_INPUT_PUSH)
			  ? BT_ACS_CONFIRMATION_INPUT_OOB_PUSH
			  : 0) |
		 (IS_ENABLED(CONFIG_BT_ACS_CONFIRMATION_INPUT_NUMERIC)
			  ? BT_ACS_CONFIRMATION_INPUT_OOB_INPUT_NUMERIC
			  : 0)),

	/* Numeric confirmation output capabilities */
	.confirmation_output_oob_number_max_value = CONFIG_BT_ACS_CONFIRMATION_OUTPUT_MAX_VALUE,
	.confirmation_output_oob_number_capabilities =
		((IS_ENABLED(CONFIG_BT_ACS_CONFIRMATION_OUTPUT_BEEP)
			  ? BT_ACS_CONFIRMATION_OUTPUT_OOB_BEEP
			  : 0) |
		 (IS_ENABLED(CONFIG_BT_ACS_CONFIRMATION_OUTPUT_NUMERIC)
			  ? BT_ACS_CONFIRMATION_OUTPUT_OOB_OUTPUT_NUMERIC
			  : 0)),
};

int acs_cp_handle_get_feature(struct acs_reply *reply, struct net_buf_simple *buf)
{
	ARG_UNUSED(buf);
	LOG_DBG("feat=0x%08x prot=0x%04x", acs_features.features, acs_features.protection_methods);
	net_buf_add_mem(reply->response, &acs_features, sizeof(acs_features));
	return ACS_CP_RESULT_STAGED_REPLY;
}
